Check tests

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,3 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run pre-push
+
+if [ $? -ne 0 ]; then
+  echo "Tests failed. Aborting the push."
+  exit 1
+fi
+
+exit 0
